/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves.h"
#include <stdio.h>
#include <string.h>

int init(){
    CLIENT *clnt;

    enum clnt_stat retval_init;
    int result_init;
    char *host;

    host = getenv("IP_TUPLAS");
    if(host == NULL){

        printf("Error \n");
        return -1;
    }

    clnt = clnt_create (host, CLAVES, CLAVESVER, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        return -1;
    }
    retval_init = init_x_1(&result_init, clnt);
    if (retval_init != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }

    clnt_destroy (clnt);
    return result_init;
}

int set_value(int key, char *value1, int N_value2, double *V_value2){
    CLIENT *clnt;

    enum clnt_stat retval_set_value;
    int result_set_value;
    struct arg set_value_arg;
    char *host;

    if (N_value2 > 32 || N_value2 <= 0) {
        printf("Error: N_value2 fuera de rango \n");
        return -1;
    }

    host = getenv("IP_TUPLAS");
    if(host == NULL){
        printf("Error \n");
        return -1;
    }

    clnt = clnt_create (host, CLAVES, CLAVESVER, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        return -1;
    }
    set_value_arg.key = key;
    set_value_arg.value1 = value1;


    printf("h\n");
    printf("%i\n", N_value2 );
    printf("%i\n", *set_value_arg.N_value2 );

    *set_value_arg.N_value2 = N_value2;
    printf("a\n");
    for (int i = 0; i < N_value2; i++){
        set_value_arg.V_value2[i] = V_value2[i];
    }
    retval_set_value = set_value_x_1(set_value_arg, &result_set_value, clnt);
    if (retval_set_value != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }


    clnt_destroy (clnt);
    return result_set_value;

}

int get_value(int key, char *value1,  int *N_value2, double * V_value2) {
    CLIENT *clnt;

    int result_get_value;
    enum clnt_stat retval_get_value;
    struct arg get_value_arg;
    char *host;

    host = getenv("IP_TUPLAS");
    if (NULL == host) {
        printf("Error\n");
        return -1;
    }

    clnt = clnt_create(host, CLAVES, CLAVESVER, "tcp");
    if (clnt == NULL){
        clnt_pcreateerror (host);
        return -1;
    }

    get_value_arg.key = key;

    retval_get_value = get_value_x_1(get_value_arg, &result_get_value, clnt);
    if (retval_get_value != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }

    strcpy(value1, get_value_arg.value1);
    *N_value2 = *get_value_arg.N_value2;

    for (int i = 0; i < *N_value2; i++) {
        V_value2[i] = get_value_arg.V_value2[i];
    }

    clnt_destroy (clnt);
    return result_get_value;
}

int modify_value(int key, char *value1, int N_value2, double *V_value2){
    CLIENT *clnt;

    enum clnt_stat retval_modify_value;
    int result_modify_value;
    struct arg modify_value_arg;
    char *host;

    if (N_value2 > 32 || N_value2 <= 0) {
        printf("Error: N_value2 fuera de rango \n");
        return -1;
    }

    host = getenv("IP_TUPLAS");
    if(host == NULL){
        printf("Error \n");
        return -1;
    }

    clnt = clnt_create (host, CLAVES, CLAVESVER, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        return -1;
    }

    modify_value_arg.key = key;
    strcpy(modify_value_arg.value1, value1);
    *modify_value_arg.N_value2 = N_value2;
    for (int i = 0; i < N_value2; i++){
        modify_value_arg.V_value2[i] = V_value2[i];
    }


    retval_modify_value = modify_value_x_1(modify_value_arg, &result_modify_value, clnt);
    if (retval_modify_value != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }
    clnt_destroy (clnt);
    return  result_modify_value;

}


int delete_key(int key){
    CLIENT *clnt;

    enum clnt_stat retval_delete_key;
    int result_delete_key;

    char *host;

    host = getenv("IP_TUPLAS");
    if(host == NULL){
        printf("Error \n");
        return -1;
    }

    clnt = clnt_create (host, CLAVES, CLAVESVER, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        return -1;
    }

    retval_delete_key = delete_key_x_1(key, &result_delete_key, clnt);
    if (retval_delete_key != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }

    clnt_destroy (clnt);
    return result_delete_key;
}


int exist(int key) {
	CLIENT *clnt;

	enum clnt_stat retval_exist;
	int result_exist;
    char *host;

    host = getenv("IP_TUPLAS");
    if(host == NULL){
        printf("Error \n");
        return -1;
    }

    clnt = clnt_create (host, CLAVES, CLAVESVER, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        return -1;
    }


	retval_exist = exist_x_1(key, &result_exist, clnt);
	if (retval_exist != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	clnt_destroy (clnt);
    return result_exist;

}


int main (void ) {
    int res = init();
    printf("Init devuelve %d\n", res);

    // Llamada a la función set_value
    int N_value2 = 32;
    double V_value2[N_value2];
    for (int i = 0; i < N_value2; i++) {V_value2[i] = (double)i;}
    res = set_value(10, "prueba de cadena", N_value2, V_value2);
    printf("Set_value devuelve %d\n", res);

    exit (0);
}
