/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves.h"

int init(void) {
    CLIENT *clnt;
    int result_1;

    host = getenv("IP_TUPLAS");
    if (NULL == host) {
        printf("Error\n");
        return -1;
    }

    cltn = clnt_create(host, CLAVES, CLAVESVER, "tcp") {
        clnt_pcreateerror (host);
        exit (1);
    }

    retval_1 = init_1(&result_1, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }

    clnt_destroy (clnt);
    return result_1;
}

int get_value(int key, char *value1,  int * N_value2, double * V_value2) {
    CLIENT *clnt;
    int result_2;
    struct arg args;

    host = getenv("IP_TUPLAS");
    if (NULL == host) {
        printf("Error\n");
        return -1;
    }

    cltn = clnt_create(host, CLAVES, CLAVESVER, "tcp") {
        clnt_pcreateerror (host);
        exit (1);
    }

    args.key = key;
    strcpy(args.value1, value1);
    args.N_value2 = *N_value2;

    for (int i = 0; i < *N_value2) {
        args.V_value2[i] = N_value2[i];
    }

    retval_2 = get_value_1(args, &result2, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }

    clnt_destroy (clnt);

    strcpy(value1, args.value1);
    *N_value2 = args.N_value2;

    for (int i = 0; i < *N_value2; i++) {
        V_value2[i] = args.V_value2[i];
    }

    return result_2;
}

int main (int argc, char *argv[])
{
    char value1[256];
    int N_value2 = 2;
    double V_value2[2]= {1.0, 2.0};

    int result = get_value(0x123, value1, &N_value2, V_value2) ;
	printf("result = %d\n", result);
    return 0;
}
