/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves.h"

bool_t
init_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
get_value_1_svc(struct arg arg, int *result,  struct svc_req *rqstp)
{
	pthread_mutex_lock(&mutex);
    ////////PEGAR CÓDIGO
    *result = server_get_value(arg.key, arg.value1, &(arg.N_value2), arg.V_value2);
    pthread_mutex_unlock(&mutex);

	return 1;
}

int
claves_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */
    // rpcinfo-p localhost (la IP del pc)

	return 1;
}
